// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"fido2/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUseCase {
	mock := &MockUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserUseCase is an autogenerated mock type for the UserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

type MockUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUseCase) EXPECT() *MockUserUseCase_Expecter {
	return &MockUserUseCase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) CreateUser(user *entity.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *entity.User
func (_e *MockUserUseCase_Expecter) CreateUser(user interface{}) *MockUserUseCase_CreateUser_Call {
	return &MockUserUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *MockUserUseCase_CreateUser_Call) Run(run func(user *entity.User)) *MockUserUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.User
		if args[0] != nil {
			arg0 = args[0].(*entity.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUseCase_CreateUser_Call) Return(err error) *MockUserUseCase_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_CreateUser_Call) RunAndReturn(run func(user *entity.User) error) *MockUserUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) DeleteUser(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserUseCase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - id string
func (_e *MockUserUseCase_Expecter) DeleteUser(id interface{}) *MockUserUseCase_DeleteUser_Call {
	return &MockUserUseCase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", id)}
}

func (_c *MockUserUseCase_DeleteUser_Call) Run(run func(id string)) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) Return(err error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) RunAndReturn(run func(id string) error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByChallenge provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetUserByChallenge(challenge string) (*entity.User, error) {
	ret := _mock.Called(challenge)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByChallenge")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return returnFunc(challenge)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = returnFunc(challenge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(challenge)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetUserByChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByChallenge'
type MockUserUseCase_GetUserByChallenge_Call struct {
	*mock.Call
}

// GetUserByChallenge is a helper method to define mock.On call
//   - challenge string
func (_e *MockUserUseCase_Expecter) GetUserByChallenge(challenge interface{}) *MockUserUseCase_GetUserByChallenge_Call {
	return &MockUserUseCase_GetUserByChallenge_Call{Call: _e.mock.On("GetUserByChallenge", challenge)}
}

func (_c *MockUserUseCase_GetUserByChallenge_Call) Run(run func(challenge string)) *MockUserUseCase_GetUserByChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetUserByChallenge_Call) Return(user *entity.User, err error) *MockUserUseCase_GetUserByChallenge_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserUseCase_GetUserByChallenge_Call) RunAndReturn(run func(challenge string) (*entity.User, error)) *MockUserUseCase_GetUserByChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetUserByID(id string) (*entity.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserUseCase_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - id string
func (_e *MockUserUseCase_Expecter) GetUserByID(id interface{}) *MockUserUseCase_GetUserByID_Call {
	return &MockUserUseCase_GetUserByID_Call{Call: _e.mock.On("GetUserByID", id)}
}

func (_c *MockUserUseCase_GetUserByID_Call) Run(run func(id string)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) Return(user *entity.User, err error) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) RunAndReturn(run func(id string) (*entity.User, error)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetUserByUsername(username string) (*entity.User, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entity.User, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = returnFunc(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserUseCase_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockUserUseCase_Expecter) GetUserByUsername(username interface{}) *MockUserUseCase_GetUserByUsername_Call {
	return &MockUserUseCase_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", username)}
}

func (_c *MockUserUseCase_GetUserByUsername_Call) Run(run func(username string)) *MockUserUseCase_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetUserByUsername_Call) Return(user *entity.User, err error) *MockUserUseCase_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserUseCase_GetUserByUsername_Call) RunAndReturn(run func(username string) (*entity.User, error)) *MockUserUseCase_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetUsers() ([]*entity.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entity.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entity.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserUseCase_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
func (_e *MockUserUseCase_Expecter) GetUsers() *MockUserUseCase_GetUsers_Call {
	return &MockUserUseCase_GetUsers_Call{Call: _e.mock.On("GetUsers")}
}

func (_c *MockUserUseCase_GetUsers_Call) Run(run func()) *MockUserUseCase_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserUseCase_GetUsers_Call) Return(users []*entity.User, err error) *MockUserUseCase_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserUseCase_GetUsers_Call) RunAndReturn(run func() ([]*entity.User, error)) *MockUserUseCase_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) UpdateUser(user *entity.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserUseCase_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user *entity.User
func (_e *MockUserUseCase_Expecter) UpdateUser(user interface{}) *MockUserUseCase_UpdateUser_Call {
	return &MockUserUseCase_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *MockUserUseCase_UpdateUser_Call) Run(run func(user *entity.User)) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.User
		if args[0] != nil {
			arg0 = args[0].(*entity.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUseCase_UpdateUser_Call) Return(err error) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_UpdateUser_Call) RunAndReturn(run func(user *entity.User) error) *MockUserUseCase_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}